#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
# Requirements:
# You must use the while loop (for and until are forbidden)


i=0
while [ $i -lt 10 ]
do
    echo "Best School"
    i=$((i+1))
done
