#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#The checker is running on Docker,

cp /etc/hosts ~/hosts.new
echo -e "127.0.0.2\tlocalhost\n8.8.8.8\tfacebook.com" > ~/hosts.new
cp -f ~/hosts.new /etc/hosts
